camera:
  from: [3.0, 8.5, -14.5]
  to: [0.0, 0.0, 0.0]
  up: [0.0, 1.0, 0.0]
  width: 800
  height: 800
  fov_radian: 0.89 # PI/3.5

light:
  position: [-5.0, 10.0, -10.0]
  color: [1.0, 1.0, 1.0]

objects:
  - material:
      color: [0.8, 0.8, 0.8]
      ambient: 0.7
      diffuse: 0.8
    shape: Cube